### PR TITLE
DMBM 864 & 865 LEARN - Link all the guidance pages in the journey

### PR DESCRIPTION
**Pull request by AShaww**
Implemented "link all guidance pages" in the journey.

In this PR we have added additional resourceDetails to the session data, when the user is on the /find/{resourceId} or find/{resourceId}/acquirer routes, we now pass the organisationTitle and organisationTitle to the learn route, specific to the /learn/data-sharing-questions

image
image

The links above links will take you to /learn/articles/data-sharing-questions 
image

### Additional changes

Links in Related data now work correctly for assets we currently have:
image

### CODE REVIEW

**Comment by duncanheron** [comment]
What happens is the user makes thier way to the `/learn/articles/data-sharing-questions` page without first visiting a resource? 
I also cant see any use of `resourceID: "Default RequestID",`

**Comment by AShaww** [comment]
> What happens is the user makes their way to the `/learn/articles/data-sharing-questions` page without first visiting a resource?`
they should see the default values of:
image

>I also cant see any use of `resourceID: "Default RequestID",
this was left over from a test on the backlink, will remove. Thanks Duncan

**Comment by kjoshi** [comment]
Could the default values be changed to:
`((data-resource-name))` -> `"the data asset"`
`((department-name))` -> `the data asset publisher` or `the data asset supplier`

so that it's a bit more seamless?

**Comment by AShaww** [comment]
> Could the default values be changed to: `((data-resource-name))` -> `"the data asset"` `((department-name))` -> `the data asset publisher` or `the data asset supplier`
> 
> so that it's a bit more seamless?

This has been implemented, thanks @kjoshi for the suggestion

**Review by madz-lw — APPROVED** [review]
LGTM thanks Amir 👍

**Pull request merged**
