### PR TITLE
DMBM- 981/resource tables spreading beyond column

### PR DESCRIPTION
**Pull request by madz-lw**
This PR fixes the issues with styling on the resource page where content was not wrapping inside the data tables. I have also added styling so that we maintain window responsivity and the page is displayed well on small screens.

image

And mobile sized...
image

### CODE REVIEW

**Review by AShaww — APPROVED** [review]
I think this is good, but might be a better idea to remove the resource-page class and have 

```
.govuk-table__cell {
  a.govuk-link {
    word-break: break-word;
    display: block;
    overflow-wrap: break-word;
  }
}
```

As mentioned on Slack, to handle any case if a link spans too far out of the container across all pages

**Review by gabimartini — APPROVED** [review]
It's looking great Maddie 🥳

**Review by madz-lw — COMMENTED** [review]
Thanks Amir, after a bit of experimenting, I've removed the `resource-page` class from the specific tables and am instead targeting `.govuk-table` so that the whole styles are applied to tables throughout the build. We only target 
```
.govuk-table__cell {
  a.govuk-link {
```
on this page so hopefully applying the whole table style will address these concerns. I've kept a `resource-container` class on the parent div of the page so that we can keep the content from overspilling on the whole page (which was happening when the screen was resized).

**Review by kjoshi — APPROVED** [review]
LGTM 👍

**Pull request merged**
