### PR TITLE
Dmbm 618/data subjects step

### PR DESCRIPTION
**Pull request by gabimartini**

### CODE REVIEW

**Review by kjoshi — CHANGES_REQUESTED** [review]
We need to remove the ` || {}` on line 98 of `acquirerRoutes.ts`.

The default value for the text fields in the form template is an empty string`''`, which is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) in javascript, so the empty string is getting replaced with an empty object `{}` and rendered as `[object Object]` in the text field:

image

@gabimartini could you replace line 98 in `acquirerRoutes.ts` so that it just passes the `stepData.value` through to the template:
`savedValue: stepData.value`

(cc @AShaww: FYI)

**Comment by AShaww** [comment]
The fix for this has been implemented and merged into 608, should be good to update this branch 👍🏼

**Comment by gabimartini** [comment]
Merged! @AShaww @kjoshi

**Review by kjoshi — APPROVED** [review]
Looks good to me, thanks Gabi 👍

**Review by AShaww — APPROVED** [review]
Looks good to me, thanks Gabi 👍🏼

**Pull request merged**
